services:
  qbit-rectificarr:
    build: .
    container_name: qbit-rectificarr
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
      CONFIG_PATH: /config/config.json
      MODE: loop
      RUN_INTERVAL: 300
      LOG_LEVEL: INFO
      LOG_FILE: /config/logs/qbit-rectificarr.log
    volumes:
      - ./config:/config
